CRUD/CRUDWeb/Models/ErrorViewModel.cs
namespace CRUDWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD/CRUDWeb/Models/List.cs
using System.ComponentModel.DataAnnotations;

namespace CRUDWeb.Models
{
    public class List
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime Created { get; set; } = DateTime.Now;
    }
}

CRUD/CRUDWeb/Controllers/HomeController.cs
using CRUDWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CRUDWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRUD/CRUDWeb/Controllers/ListController.cs
using CRUDWeb.Data;
using CRUDWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace CRUDWeb.Controllers
{
    public class ListController : Controller
    {
        private readonly WebAppDbContext _db;

        public ListController(WebAppDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<List> objCategoryList = _db.Lists.ToList();
            return View(objCategoryList);
        }

        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(List obj)
        {
            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("name", "The name and description can't match.");
            }
            if(ModelState.IsValid)
            {
                _db.Lists.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj); 
            
        }

        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0) 
            { 
                return NotFound();
            }
            var listFromDb = _db.Lists.Find(id);
            if (listFromDb == null)
            {
                return NotFound();
            }
            return View(listFromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(List obj)
        {
            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("name", "The name and description can't match.");
            }
            if (ModelState.IsValid)
            {
                _db.Lists.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var listFromDb = _db.Lists.Find(id);
            if (listFromDb == null)
            {
                return NotFound();
            }
            return View(listFromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete_(int? id)
        {
            var obj = _db.Lists.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
                _db.Lists.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

    }
}

CRUD/CRUDWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CRUD/CRUDWeb/Views/List/Add.cshtml
@model List

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h1 class="text-primary">Add New</h1>
        </div>
    </div>
    <div class="mb=3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mb=3">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <hr />
    <button type="submit" class="btn btn-primary">Add</button>
    <a asp-controller="List" asp-action="Index" class="btn btn-warning">Back</a>


</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CRUD/CRUDWeb/Views/List/Delete.cshtml
@model List

<form method="post" asp-action="Delete_">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h1 class="text-primary">Delete</h1>
        </div>
    </div>
    <div class="mb=3">
        <label asp-for="Name"></label>
        <input asp-for="Name" disabled class="form-control" />
    </div>
    <div class="mb=3">
        <label asp-for="Description"></label>
        <input asp-for="Description"  disabled class="form-control" />
    </div>
    <hr />
    <div>
    <button type="submit" class="btn btn-primary">Delete</button>
    <a asp-controller="List" asp-action="Index" class="btn btn-warning">Back</a>
    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CRUD/CRUDWeb/Views/List/Edit.cshtml
@model List

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h1 class="text-primary">Edit</h1>
        </div>
    </div>
    <div class="mb=3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mb=3">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <hr />
    <div>
    <button type="submit" class="btn btn-primary">Update</button>
    <a asp-controller="List" asp-action="Index" class="btn btn-warning">Back</a>
    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CRUD/CRUDWeb/Views/List/Index.cshtml
@model IEnumerable<List>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h1 class="text-primary">List</h1>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="List" asp-action="Add" class="btn btn-primary text-end"><i class="bi bi-plus-square"> Add New</i></a>
        </div>
    </div>
</div>

<table class="table table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
                Time created
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td style="width:30%">
                    @obj.Name
                </td>
                <td style="width:30%">
                    @obj.Description
                </td>
                <td style="width:30%">
                    @obj.Created
                </td>
                <td>
                    <div clas="btn-group">
                        <a asp-controller="List" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-info"><i class="bi bi-pencil-square"></i></a>
                        <a asp-controller="List" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger"><i class="bi bi-trash3"></i></a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

CRUD/CRUDWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUDWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUDWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUDWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="List" asp-action="Index">List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CRUDWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>